name: Pinautomaat
main: mohagames\pinautomaat\Pinautomaat
version: 1.1.0
api: 3.0.0
author: Mohagames205

description: Pinnen met gemak!
website: https://github.com/Mohagames205/Pinautomaat

commands:
  atm:
    description: ATM main command
    permission: pinautomaat.admin

permissions:
  atm.create:
    default: op
  atm.delete:
    default: op
