name: Pinautomaat
main: mohagames\EasyATM\EasyATM
version: 1.1.0
api: 3.0.0
author: Mohagames205

description: Pinnen met gemak!
website: https://github.com/Mohagames205/EasyATM

commands:
  atm:
    description: ATM main command
    permission: EasyATM.admin

permissions:
  atm.create:
    default: op
  atm.delete:
    default: op
